"""
Generated by running where 2016 8 29 -I (interactive), and then doing the following:

plt.xkcd()

idx = np.logical_and(np.logical_and(v3.filter(station='NYALES20'), v3.filter(station='HARTRAO')), v3.filter(source='0202+319'))

plt.plot(v3.time.utc.datetime[idx], -v3.observed_delay[idx] / 1000, 'ro'); plt.axis((736205.94, 736206.22, 2500, 8200)); plt.title('Malinger, Ny-Alesund - Hartebeesthoek'); plt.savefig('malinger.png', bbox_inches='tight', transparent=True, dpi=200); plt.show()
"""
