# This setup is for downloading the GPT3 external library
#
# To use it, run the download.py script with `gpt3` as an option:
#
#     python download.py gpt3
#
# See https://vmf.geo.tuwien.ac.at/ for information about GPT3


[library]
name = GPT3
source_url = https://vmf.geo.tuwien.ac.at/codes/
target_dir = external/gpt3


[preprocess]
rm -rf external/gpt2w/src                        = remove directory 'external/gpt3/src'


[files]
__target__            = src
gpt3_1.grd            = 
gpt3_1.f90            =
vmf3_ht.f90           = 


[postprocess]
# Always do this last. Successful copy of .pyf file will trigger the makefile to continue as normal
cp external/gpt3/gpt3.pyf external/gpt3/src   = Copy 'gpt3.pyf' from 'external/gpt3' to 'external/gpt3/src'
